apiVersion: windows.k8s.io/v1
kind: GMSACredentialSpec
metadata:
  name: gmsa-webapp01  # This is an arbitrary name but it will be used as a reference
credspec:
  ActiveDirectoryConfig:
    GroupManagedServiceAccounts:
    - Name: WebApp01   # Username of the GMSA account
      Scope: GMSAPING  # NETBIOS Domain Name
    - Name: WebApp01   # Username of the GMSA account
      Scope: gmsaping.com # DNS Domain Name
  CmsPlugins:
  - ActiveDirectory
  DomainJoinConfig:
    DnsName: gmsaping.com  # DNS Domain Name
    DnsTreeName: gmsaping.com # DNS Domain Name Root
    Guid: bae5a583-612f-4e8a-9b69-9df1c5c9b81a  # GUID
    MachineAccountName: WebApp01 # Username of the GMSA account
    NetBiosName: GMSAPING  # NETBIOS Domain Name
    Sid: S-1-5-21-922537405-2102905723-2121843970 # SID of GMSA
